### ISSUE TITLE
#7 Test: email + password for Sign-in validation

### ISSUE THREAD

**Issue by zepherine2006DEV** [lucianmot/acebook-off-the-rails#12]
See trello ticket #7

**Comment by zepherine2006DEV** [comment]
Included some unrelated refactoring to fix rubocop offences.

**Comment by lucianmot** [comment]
We (james + lucian) are taking over.

**Comment by lucianmot** [comment]
Completed feature test added log out link to the index page(we needed this in order to be able to run our feature tests, explanation once you sign up you are automatically signed in as well, so thus we couldn't test the sign in function)
